### PR TITLE
README: direct users to XQuartz.org

### PR DESCRIPTION
**Pull request by johannkoenig**
Very few packages can be installed without x11-dev. Include
instructions on resolving this dependency.

### CODE REVIEW

**Comment by TheSin-** [comment]
I'm trying to determine if I should accept PRs here, or if PRs should be made upstream as I sync changes from upstream.

**Comment by johannkoenig** [comment]
Also, would you prefer this on the main branch or 1.16? I need 1.16 to run on OS X 12.2

**Comment by TheSin-** [comment]
I'd say move these to fink/master and I'll back port them once accepted.  They don't remember have to do with this PR and I don't want to add more to have reviewed as it's taking so long already.

I really hope to have 1.16 merged soon there is a thread for it on fink-core, so I'm hoping really soon.

**Comment by TheSin-** [comment]
I'd say move these to fink/master and I'll back port them once accepted.  They don't remember have to do with this PR and I don't want to add more to have reviewed as it's taking so long already.

**Comment by johannkoenig** [comment]
Thanks. I moved this one to https://github.com/fink/fink/pull/242

**Pull request closed without merging**
