### PR TITLE
Update several bootstrap packages to match version in fink-distributions

### PR DESCRIPTION
**Pull request by nieder**
Did not touch gettext/libiconv/dpkg's internal gettext useage. Also did not touch texinfo (6.3 here vs 6.8 in dists) because the changes are more substantial and I don't know enough about them.

Also, don't know why the PR is showing the past 7 commits by TheSin- to the tree. The last commit is the only one from me.

Tested to bootstrap cleanly with these updates on 10.14.6

### CODE REVIEW

**Comment by TheSin-** [comment]
trying to figure out how to get just the one commit, I have never done a cherry pick in the GitHub UI.

I might have to take a diff and commit this by hand if that is okay?

**Comment by nieder** [comment]
[0001-update-several-package-descriptions.patch.txt](https://github.com/TheSin-/fink/files/7592629/0001-update-several-package-descriptions.patch.txt)

I've attached the patch for my individual commit that can be applied via `git am`

**Comment by TheSin-** [comment]
And I'm off to read about `git am` ;)

**Comment by TheSin-** [comment]
Done via git am, thanks @nieder

**Pull request closed without merging**
