### PR TITLE
Big Sur 11.3 support

### PR DESCRIPTION
**Pull request by nieder**
Allow bootstrapping on macOS 11.3, which brings along a new perl-5.30.2

### CODE REVIEW

**Comment by nieder** [comment]
Added support for 11.5 (still in beta, but it bootstraps).
Also, the changes from PR #8 are also needed to define $gcc.

**Comment by TheSin-** [comment]
Has this been sorted and tested so I can merge?

**Comment by nieder** [comment]
I've tested using the current string comparison method that dates back to 10.7. I haven't had time to replace and test using numerical comparison operators.

**Comment by nieder** [comment]
I propose to merge this first and then we can go and fix the string vs numerical comparison issue. It might not be optimal, but the string comparison works.

**Comment by nieder** [comment]
Pushed a bunch of updates to answer raised issues.
* Now knows about Monterey macOS12 (but can't install there yet)
* uses numerical comparison rather than string comparison for the perl version

Note: monterey beta1 uses perl5.30.3. which means a NEW system-perl.

**Comment by nieder** [comment]
@dmacks for issue you raised about numerical vs string comparison
487ad02 and 986e3a8

**Comment by dmacks** [comment]
Comparisons look fine.

**Pull request merged**
